### ISSUE TITLE
上传视频后，点击搜索后页面变成空白

### ISSUE THREAD

**Issue by inkn** [ArthurKing01/jina-clip#3]
平台 win11 + wsl2 ubuntu 20.04
python 版本 3.9

```
[Nest] 7832  - 2022/07/09 13:07:50     LOG [NestApplication] Nest application successfully started +6ms
[From Jina]
 DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses (raised from /home/lin/venv/lib/python3.9/site-packages/past/builtins/misc.py:45)

[From Jina]
 DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:228)

[From Jina]
 DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:295)
DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:311)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
 (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:328)

[From Jina]
 DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:228)

[From Jina]
 DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:295)
DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:311)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
 (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:328)

[From Jina]
 DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /home/lin/venv/lib/python3.9/site-packages/transformers/image_utils.py:143)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
 (raised from /home/lin/venv/lib/python3.9/site-packages/transformers/models/clip/feature_extraction_clip.py:67)

[From Jina]
 DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /home/lin/venv/lib/python3.9/site-packages/transformers/models/clip/feature_extraction_clip.py:184)

[From Jina]
 DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:228)

[From Jina]
 DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:295)
DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:311)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
 (raised from /home/lin/venv/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py:328)

[From Jina]
 DeprecationWarning: Setting `workspace` via `metas.workspace` is deprecated. Instead, use `f.add(..., workspace=...)` when defining a a Flow in Python; the `workspace` parameter when defining a Flow using YAML; or `--workspace` when starting an Executor using the CLI. (raised from /home/lin/venv/lib/python3.9/site-packages/jina/serve/executors/__init__.py:178)

[From Jina]
[From Jina]
 ╭───── 🎉 Flow is ready to serve! ──────╮
│  🔗  Protocol                 GRPC    │
│  🏠     Local        0.0.0.0:45679    │
│  🔒   Private  172.27.217.41:45679    │
╰───────────────────────────────────────╯

{
  fieldname: 'file',
  originalname: 'ygdy8.com]梦华录-01.mp4',
  encoding: '7bit',
  mimetype: 'video/mp4',
  buffer: <Buffer 00 00 00 20 66 74 79 70 69 73 6f 6d 00 00 02 00 69 73 6f 6d 69 73 6f 32 61 76 63 31 6d 70 34 31 00 22 d6 f8 6d 6f 6f 76 00 00 00 6c 6d 76 68 64 00 00 ... 586443253 more bytes>,
  size: 586443303
} [Object: null prototype] {} 35bf29b0-febc-11ec-859b-178d405baa03
[Nest] 7480  - 2022/07/09 12:42:57     LOG 保存成功! path: /home/lin/jina-clip/hello-jina2/static/videos/35bf29b0-febc-11ec-859b-178d405baa03/ygdy8.com]梦华录-01.mp4
[From Jina]
 video_loader extract 1657341777.4362361
video chunks: 0
INFO   VideoLoader@7521 received                             [07/09/22 12:42:57]
       35bf29b0-febc-11ec-859b-178d405baa03|**|ygdy8.com]梦…

[From Jina]
 E0709 12:42:57.442448306    7521 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers

[From Jina]
 E0709 12:42:57.818938676    7521 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers

[From Jina]
 ERROR  gateway/rep-0@7525 Error while getting responses from [07/09/22 12:43:59]
       deployments: failed to connect to all addresses
       |Gateway: Communication error with deployment
       video_loader at address 0.0.0.0:56092. Head or worker
       may be down.

[Nest] 7480  - 2022/07/09 12:43:59     LOG tornado index succuss
[From Tonardo] ERROR:tornado.application:Uncaught exception POST / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8900', method='POST', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/lin/venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/lin/jina-clip/glue/web.py", line 30, in post
    async for resp in c.post('/index', inputs=inputs):
  File "/home/lin/venv/lib/python3.9/site-packages/jina/clients/mixin.py", line 234, in post
    async for result in c._get_results(
  File "/home/lin/venv/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 133, in _get_results
    raise e
  File "/home/lin/venv/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 99, in _get_results
    raise ConnectionError(my_details) from None
ConnectionError: failed to connect to all addresses |Gateway: Communication error with deployment video_loader at address 0.0.0.0:56092. Head or worker may be down.

[Nest] 7480  - 2022/07/09 12:44:13     LOG 35bf29b0-febc-11ec-859b-178d405baa03
[From Jina]
 UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:178.) (raised from /home/lin/venv/lib/python3.9/site-packages/docarray/proto/io/ndarray.py:149)

```

search 接口返回：201
code: 0
data: [{text: "water", matches: []}]
message: "ok"

**Comment by ArthurKing01** [comment]
单次上传尽量用10分钟以内的视频吧，太长的电脑撑不住，一个思路是提前将视频切成小段，分别上传

**Comment by inkn** [comment]
上传了个 5 分钟的视频还是这样

**Comment by BingChillinggg** [comment]
我也是这种情况，请问lz解决了吗？

**Comment by bakaEC** [comment]
我通过直接升级numpy pillow torchvision google jina到最新版解决了报错
